language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_script:
  - npm install jshint -g
  - jshint --version
  - curl -s https://raw.github.com/jlipps/sausage-bun/master/givememysausage.php | php
script:
  - phpunit
  - jshint --verbose --show-non-errors util.js
  - php test/coverage-checker.php clover.xml 45
env:
  global:
  - SAUCE_USERNAME=seblucas 
  - secure: VVxocvmz6WYr3tZSTA42M/LUhaHoBWw5onh85hnquoMaxspd3tDCyfQIowTTmEXikRh2T0CkTH7X3dhVwRTd/Ha9isja1qDo9Lc2flGCoWICF7WFZuom084+d+O+EWx4WZMAw4Lz4w6a5xflpPKnzNs9B0+de0BdTlQ5qSXVrcA=
addons:
  sauce_connect: true
